#!/bin/bash


# Check if the number of command line arguments is less than 1
if [ $# -lt 1 ]; then
    echo "Usage: $0 <file_path> <url> [install] [test] [dev]"
    exit 1
fi

# Obtain command line argument
arg=$1
# echo "Argument: $arg";

# Install dependencies
if [ $arg == "install" ]; then
    npm install
    exit 0
fi

# Run the test suite
if [ $arg == "test" ]; then
    npm run auto-grader-test | grep -v "JSON report written to"
    npm run build
    node dist/utils/reports/extract-results.js
    exit 0
fi

# Check if the argument is a file path
if [ -f $arg ]; then
    # Compile TS files
    npm run build
    # Pass the file path index.js
    node dist/index.js --file "$arg"
    exit 0
fi

exit 1

